---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: 7-demo-source-oci-bb-app-7-7-0
  namespace: flux-system
spec:
  interval: 10s
  provider: generic
  ref:
    tag: 7.7.0-0bb2691
  secretRef:
    name: ghcr-auth
  url: oci://ghcr.io/kodega2016/bb-app-source
