---
apiVersion: image.toolkit.fluxcd.io/v1
kind: ImageRepository
metadata:
  name: 8-demo-image-repo-bb-app
  namespace: flux-system
spec:
  image: docker.io/kodega2016/block-buster-dev
  interval: 10s
